/**
 * types/ticket.ts — Shared Ticket Type Definitions
 *
 * PURPOSE:
 * ─────────
 * These interfaces represent the shape of ticket data as it travels from
 * the database → API route → client component. They are used by:
 *
 *   - app/dashboard/page.tsx   (user sees their own tickets)
 *   - app/admin/page.tsx       (admin sees all tickets with user info)
 *   - components/TicketTable.tsx
 *
 * WHY NOT USE PRISMA'S GENERATED TYPES DIRECTLY?
 * ─────────────────────────────────────────────────
 * Prisma's generated `Ticket` type uses `Date` for `createdAt`/`updatedAt`.
 * Once serialized over JSON (from API route to the client), those become
 * plain strings. Using our own interface with `string` for the date fields
 * avoids runtime confusion and type errors in client components.
 *
 * FIELD DOCUMENTATION:
 * ─────────────────────
 * id           — CUID string. Primary key generated by Prisma (@default(cuid())).
 * subject      — Short description of the problem. Shown as the card title.
 * description  — Full details of the issue. Shown in the admin expanded panel.
 * phone        — Contact number for the employee. Pre-filled from profile if saved.
 * computerName — Hostname of the affected machine (e.g. "PC-ALON-01").
 *                Used by the tech to locate the machine on the network.
 * urgency      — One of: "נמוך" | "בינוני" | "גבוה" | "דחוף"
 *                Controls queue sort order in admin (דחוף first, נמוך last).
 * category     — One of: "חומרה" | "תוכנה" | "רשת" | "מדפסת" | "אחר"
 *                Used for filtering and reporting.
 * status       — One of: "פתוח" | "בטיפול" | "סגור"
 *                Changed by admins via PATCH /api/tickets.
 * createdAt    — ISO 8601 datetime string. Set automatically by Prisma.
 * updatedAt    — ISO 8601 datetime string. Updated automatically on any change.
 * userId       — Foreign key referencing User.id.
 */

/** The base ticket shape returned by GET /api/tickets for regular users. */
export interface Ticket {
  id: string
  subject: string
  description: string
  phone: string
  computerName: string
  urgency: string
  category: string
  platform: string
  status: string
  createdAt: string
  updatedAt: string
  userId: string
}

/**
 * Extended ticket shape returned by GET /api/tickets for admins.
 * Includes a nested `user` object from Prisma's `include` clause,
 * so admins can see who submitted each ticket without a separate query.
 */
export interface TicketWithUser extends Ticket {
  user?: {
    /** Display name of the submitting employee. May be null if not set. */
    name?: string | null
    /** Google email of the submitting employee. */
    email?: string | null
  }
}
