/**
 * types/ticket.ts — Shared Ticket Type Definitions
 *
 * PURPOSE:
 * ─────────
 * These interfaces represent the shape of ticket data as it travels from
 * the database → API route → client component. They are used by:
 *
 *   - app/dashboard/page.tsx   (user sees their own tickets)
 *   - app/admin/page.tsx       (admin sees all tickets with user info)
 *   - components/TicketTable.tsx
 *
 * WHY NOT USE PRISMA'S GENERATED TYPES DIRECTLY?
 * ─────────────────────────────────────────────────
 * Prisma's generated `Ticket` type uses `Date` for `createdAt`/`updatedAt`.
 * Once serialized over JSON (from API route to the client), those become
 * plain strings. Using our own interface with `string` for the date fields
 * avoids runtime confusion and type errors in client components.
 *
 * FIELD DOCUMENTATION:
 * ─────────────────────
 * id           — CUID string. Primary key generated by Prisma (@default(cuid())).
 * subject      — Short description of the problem. Shown as the card title.
 * description  — Full details of the issue. Shown in the admin expanded panel.
 * phone        — Contact number for the employee. Pre-filled from profile if saved.
 * computerName — Hostname of the affected machine (e.g. "PC-ALON-01").
 *                Used by the tech to locate the machine on the network.
 * urgency      — One of: "נמוך" | "בינוני" | "גבוה" | "דחוף"
 *                Controls queue sort order in admin (דחוף first, נמוך last).
 * category     — One of: "חומרה" | "תוכנה" | "רשת" | "מדפסת" | "אחר"
 *                Used for filtering and reporting.
 * status       — One of: "פתוח" | "בטיפול" | "סגור"
 *                Changed by admins via PATCH /api/tickets.
 * createdAt    — ISO 8601 datetime string. Set automatically by Prisma.
 * updatedAt    — ISO 8601 datetime string. Updated automatically on any change.
 * userId       — Foreign key referencing User.id.
 */

/** The base ticket shape returned by GET /api/tickets for regular users. */
export interface Ticket {
  id: string
  ticketNumber: number
  assignedTo: string
  subject: string
  description: string
  phone: string
  computerName: string
  urgency: string
  category: string
  platform: string
  status: string
  holdReason?: string | null   // set when status = "בהמתנה", null otherwise
  type?: string                // "ticket" (HDTC-N) or "request" (REQ-N) — v3.87, lib/ticketType.ts
  mergedIntoId?: string | null // set when this ticket was merged into another (v3.92, lib/ticketMerge.ts)
  createdAt: string
  updatedAt: string
  userId: string
}

/**
 * Extended ticket shape returned by GET /api/tickets for admins.
 * Includes a nested `user` object from Prisma's `include` clause,
 * so admins can see who submitted each ticket without a separate query.
 */
export interface TicketWithUser extends Ticket {
  user?: {
    name?: string | null
    email?: string | null
  }
  /** Where a merged ticket went (v3.92) — GET /api/tickets/all includes it. */
  mergedInto?: { ticketNumber: number; type?: string | null } | null
}

export interface TicketNote {
  id: string
  ticketId: string
  content: string
  authorName: string
  authorEmail: string
  createdAt: string
}

export interface TicketAttachment {
  id: string
  ticketId: string
  /** Bytes are served by GET /api/attachments/[id] since v3.48 — list payloads
   *  carry metadata only. (Legacy pre-v3.48 rows stored base64 inline.) */
  filename?: string | null
  mimeType?: string | null
  size?: number | null
  createdAt: string
}

export interface TicketMessage {
  id: string
  ticketId: string
  content: string
  authorName: string
  authorEmail: string
  authorRole: string  // "staff" | "user"
  createdAt: string
}

export interface TicketHistoryEntry {
  id: string
  ticketId: string
  field: string       // "created" | "status" | "urgency" | "assignedTo" | "owner" | "type" | "edited" | "merged" | "mergedFrom" | "participant"
  oldValue?: string | null
  newValue?: string | null
  actorName: string
  actorEmail: string
  changedAt: string
}

/** One line of the new-employee equipment checklist (category "עובד חדש"). */
export interface TicketEquipment {
  id: string
  ticketId: string
  /** Snapshot of the FieldOption label at request time. */
  label: string
  /** How many units were requested. */
  quantity: number
  /** How many have arrived / been installed (0..quantity). */
  receivedQty: number
  receivedAt?: string | null
  receivedBy?: string | null
  createdAt: string
}

export interface TicketDetail extends TicketWithUser {
  notes: TicketNote[]
  attachments: TicketAttachment[]
  messages: TicketMessage[]
  history: TicketHistoryEntry[]
  equipment: TicketEquipment[]
  /** The ticket this one was merged into — the one the conversation goes on in (v3.92). */
  mergedInto?: { ticketNumber: number; type?: string | null } | null
  /** Tickets merged into this one. */
  mergedFrom?: { id: string; ticketNumber: number; type?: string | null; subject: string }[]
  /** People who follow the ticket without owning it — see lib/ticketAccess.ts. */
  participants?: { user: { id?: string; name: string | null; email: string } }[]
}

/** A ticket on the user's dashboard (GET /api/tickets): theirs, or one they follow (v3.92). */
export interface DashboardTicket extends TicketWithUser {
  /** "participant" when the caller follows the ticket rather than owns it. */
  role?: "owner" | "participant"
}

/** One ticket as the merge dialog shows it — GET /api/tickets/merge (v3.92). */
export interface MergePreviewTicket {
  id: string
  ticketNumber: number
  type: string
  label: string
  subject: string
  status: string
  urgency: string
  createdAt: string
  owner: { name: string | null; email: string }
  participants: { name: string | null; email: string }[]
  counts: { messages: number; notes: number; attachments: number; equipment: number }
  /** Label of the ticket it was already merged into, if any. */
  mergedInto: string | null
  /** Why a merge with this ticket as the one that stays cannot go ahead; empty when it can. */
  problems: string[]
}
